<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "memcacheddiag2"
 *
 * Auto generated by Extension Builder 2016-08-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'memcacheddiag2',
	'description' => 'Displays diagnosis information about memcache',
	'category' => 'module',
	'version' => '1.0.2',
	'author' => 'Jan Bartels',
	'author_email' => 'j.bartels@arcor.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-9.5.99',
			'php' => '7.0.0-7.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);